name: mang_mu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.0.0
  js: ^0.7.2
  postgrest: ^2.4.2

  # UI & Design
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  dotted_border: ^3.1.0
  fl_chart: ^0.65.0
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.7
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.1.1+1
  glassmorphism: ^3.0.0
  simple_animations: ^5.0.0
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  table_calendar: ^3.0.9

  # Charts
  syncfusion_flutter_charts: ^31.1.19

  # PDF & File Management
  pdf: ^3.10.4
  printing: ^5.11.2
  path_provider: ^2.1.1
  open_file: ^3.5.4
  open_file_macos: ^0.2.0
  share_plus: ^7.2.1

  # Media
  video_player: ^2.7.0
  chewie: ^1.4.0
  image_picker: ^1.2.1

  # Utilities
  intl: ^0.20.2
  http: ^1.1.0
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.10

  # Maps & Location
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
