name: mang_mu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Supabase
  supabase_flutter: ^2.0.0
  postgrest: ^2.4.2
  js: ^0.7.2
  
  # UI & Design
  provider: ^6.0.5
  flutter_rating_bar: ^4.0.0
  flutter_localizations:
    sdk: flutter
  dotted_border: ^3.1.0
  flutter_svg: ^2.0.7
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.1.1+1
  glassmorphism: ^3.0.0
  simple_animations: ^5.0.0
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  
  # Charts - استخدام syncfusion فقط
  syncfusion_flutter_charts: ^31.1.19
  
  # Media
  video_player: ^2.7.0
  chewie: ^1.4.0
  image_picker: ^1.2.1
  
  # Utilities
  intl: ^0.20.2 
  flutter_vector_icons: ^2.0.0
  http: ^1.1.0
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.2.2
  
  # Maps & Location
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - images/